include /etc/nginx/include.d/api-proxy.conf;

location /static {
   alias /var/www/public/static/;
   include /etc/nginx/include.d/allcache.conf;
}

location / {
    try_files $uri $uri/ /index.html;
    include /etc/nginx/include.d/nocache.conf;
}

include /etc/nginx/include.d/spa.conf;
